apiVersion: v1
kind: ServiceAccount
metadata:
  name: demo-api
  namespace: secops-demo
automountServiceAccountToken: false
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: demo-backend
  namespace: secops-demo
automountServiceAccountToken: false
